### ISSUE TITLE
Symbol detected as missing an import when in the same namespace

### ISSUE THREAD

**Issue by Augustin82** [sirbrillig/phpcs-import-detection#8] opened 2018-08-24 16:40 UTC
If using a class in the same namespace, there is an "missing import" report. However, the import is not needed, and is actually removed by PHP CS Fixer, for instance.

Should this be fixed? Can it be worked around? For now, I obey this sniffer and disable PHP CS Fixer =)

**Comment by sirbrillig** [comment] 2018-08-24 16:48
🤔 Interesting! I didn't know that PHP CS Fixer does that. The problem is: how do you know if a class is in the same namespace? eg: code like this:

```php
namespace Foo;

class Bar {}
```
and

```php
namespace Foo;

function doSomething() {
  return new Bar();
}
```

Using just the code, there's no easy way to determine if `Bar` is in the `Foo` namespace from within the second file. We'd have to scan all the files and look for that class, and scanning other files is a little outside the scope of most sniffs (for just one issue, it could be very slow). I wonder how PHP CS Fixer does it?

**Comment by sirbrillig** [comment] 2018-09-13 00:03
Since I can't think of a way to do this, I'm going to close this issue. If anyone can think of a way, though, I'm happy to re-open it.

**Closed as completed by sirbrillig** 2018-09-13 00:03 UTC

**Comment by andreacasarin** [comment] 2018-11-22 12:42
Hi @sirbrillig first of all thanks for the great work, I just installed this sniffer and I'm loving it.

I'd like however to do something about this issue, because right now requires to have more imports than the required ones.

I was thinking, if the code is using PSR-0 or PSR-4 would it be possibile to emulate the import of all classes in the same namespace just by getting their file name? If so, do you think it will be fast enough in this way?

**Comment by sirbrillig** [comment] 2018-11-23 15:42
Thanks @andreacasarin!

I have three thoughts about your suggestion:

1. I think it might actually work to use a PSR naming standard to find classes in the namespace, but it would only be reliable in certain circumstances (it's essentially a guess) so I'd probably want it to be a configurable option. I'll experiment with this when I have some free time.
2. With the very large codebase I'm working on right now for my job, I actually like having imports of everything, because it's nice to be able to see all the dependencies of that file at a glance at the top (unless there's absolute namespaced symbols). That said, I can definitely see how it's more work and it'd be nice if this only warned you for actual issues.
3. This sniff is a pretty lightweight syntax checker, and once we start looking at multiple files, it seems to me that we might want to use a static analyzer instead, which is designed from the ground up to do things just like this. For example, [phpstan](https://github.com/phpstan/phpstan) and [psalm](https://getpsalm.org/) I think can both look for undefined imports out of the box.

**Comment by andreacasarin** [comment] 2018-11-23 16:07
1. Totally agree, could be fragile and it has to be configurable for sure, but would be great!
2. That's a good point indeed, it's not that big work to add some imports and could help in reading the code. I'll think about that.
3. I see, thank you for the tool suggestion. Will take a look at them.
